/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mariokart.glb --transform --shadows 
Files: mariokart.glb [101.9KB] > /Users/lunakepio/gpu/public/models/mariokart-transformed.glb [26.36KB] (74%)
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from './mesh/Mesh'

export function MarioKart(props) {
  const { nodes, materials } = useGLTF('./models/mariokart-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mt_kart_Mario_S.geometry} material={materials.mt_kart_Mario_S} />
      <mesh castShadow receiveShadow geometry={nodes.mt_Kart_Mario_Tire_S001.geometry} material={materials.mt_Kart_Mario_Tire_S} position={[0, 0.22, -0.347]} />
      <mesh castShadow receiveShadow geometry={nodes.mt_mario.geometry} material={materials.mt_mario} />
      <Mesh position={[0.182, 0.61, -0.85]} rotation={[-Math.PI / 3, 0, 0]}  scale={[0.5, 0.5, 0.5]} />
    </group>
  )
}

useGLTF.preload('./models/mariokart-transformed.glb')
